language: python

services:
  - mongodb

python:
  - 2.7
  - 3.4

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda update conda --yes
  - conda config --add channels soft-matter
  - conda create -n testenv --yes pip nose python=$TRAVIS_PYTHON_VERSION pymongo six pyyaml numpy pandas scikit-image pims h5py
  - source activate testenv
  - pip install https://github.com/NSLS-II/metadataStore/zipball/master#egg=metadataStore
  - pip install https://github.com/NSLS-II/fileStore/zipball/master#egg=fileStore
  - pip install https://github.com/NSLS-II/channelarchiver/zipball/master#channelarchiver
  - pip install https://github.com/Nucleic/enaml/zipball/master#enaml
  - pip install https://github.com/Nucleic/atom/zipball/master#atom
  - pip install coveralls mongoengine
  - python setup.py install


script:
  - python run_tests.py

after_success:
  coveralls
